### ISSUE TITLE
[ REQUEST ] adding Qt App style selection to settings.

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#1118]
Hi @ra3xdh, I am currently working on to solve this feature request. Below are the tasks to be completed.

- [x] add style selection combobox to application settings (fusion, windows,windows 11 etc.). #1125
- [x] add `-style` parameter to `launchTool ` to ensure tools have the same style with the qucs-s. #1125 
- [x] refactoring some svg file to looks good on dark theme. #1122

I think we can improve svg rendering and compatability with Qt to converting all non-optimized SVG to Optimized SVG(Plain SVG) ? 

Thanks.

**Comment by ra3xdh** [comment]
> Qt to converting all non-optimized SVG to Optimized SVG(Plain SVG) ?

The SVGs used for device icons and toolbar icons were optimized using the SVGO tool https://www.drupal.org/project/svgo The other SVGs need to be checked. 

>  refactoring some svg file to looks good on dark theme.

This may require to have two sets of images: for light and dark theme. The most of device icons are rendered automatically. It is not clear how to render the icon for the dark theme. The simple color inversion will not work. Probably you need to provide an options for wire color, device color, etc for light and dark theme.  This will require to refector the components, because the colors are hardcoded now.

**Comment by dsm** [comment]
some SVGs has white background some has transparent option in tools as shown below tool screenshot. I'll remove it, and adding white-background in code as workaround but yes changing color of text and wire for dark theme.

![image](https://github.com/user-attachments/assets/9683755d-5d00-47d5-856a-4f2d72c48623)

**Comment by ra3xdh** [comment]
Yes, the images in Active filter tool are not optimized.

**Comment by dsm** [comment]
I don't remember but old issue has mentioned some svg icon has yellowish border artifact but actually svg has a border it should be remove manually.

```
<path d="M.5.5h127v127H.5z" fill-opacity="0" stroke="#fff" stroke-linecap="square" stroke-linejoin="round" style="paint-order:stroke fill markers"/>
```

![image](https://github.com/user-attachments/assets/516df582-8508-457a-9c68-b16f7c7db260)

**Comment by ra3xdh** [comment]
Implemented by #1125.
