### ISSUE TITLE
Blurry icons on HiDPI

### ISSUE THREAD

**Issue by hugolundin** [ra3xdh/qucs_s#304]
Icons are blurry when using macOS with High DPI (Retina). See the attached image (click to open the image in full screen to really see how they look). 

<img width="1542" alt="Screenshot 2023-08-22 at 10 08 21" src="https://github.com/ra3xdh/qucs_s/assets/9110669/8fe93387-1213-4629-a9c1-56eb5d99b00c">

It seems like Qt should have means for solving this: https://doc.qt.io/qt-6/highdpi.html

**TODO** from @ra3xdh :
- [x] Update toolbar icons (replace by SVG); design 8 original icons #323 
- [ ] Implement automatic generation of high-resolution components icons #334 
- [x] Redesign diagram icons (11 icons); these icons cannot be generated automatically;
- [x] Redesign paintings icons (8 icons)
- [x] Redesign simulation icons
- [x] Redesign file devices and equations icons
- [x] Redesign icons for SPICE specific section
- [x] Process all SVG images with SVG optimizer https://github.com/svg/svgo

**Comment by ra3xdh** [comment]
Yes, I am aware about issues with icons. The same appears using KDE on Linux and display scaling. 

![image](https://github.com/ra3xdh/qucs_s/assets/4920080/49d326a2-6771-43aa-a1d4-696b0f53c6dc)

The icons in the Qucs-S are designed as fixed resolution 22x22 PNG bitmaps. These icons still be inherited from Qt3 version. And this will look poor when using HiDPI resolution. The only solution for this issue is to redesign **all** button icons located in `qucs/bitmaps`. The usage of the SVG icons would be also good. But this task cannot be done in the near future because of need to redraw **all** icons. I am programmer, but not a graphical designer and cannot perform this task by myself. The contribution is highly welcome here. 

Summarizing all above, don't expect the icons to be fixed in the near years, unless someone will redesign the icons and propose a PR.

**Comment by ra3xdh** [comment]
I have started to replace toolbar icons by standard SVG icons from KDE Oxagen theme. This icon set should look good for both dark and light desktop themes. The most of toolbar icons could be replaced by standard icons. But 9 icons should be designed from scratch. Probably Oxygen icons could be used as template. I have uploaded updated icons to the `svg_icons` branch: https://github.com/ra3xdh/qucs_s/tree/svg_icons 

I don't consider the redesign of components icons because a huge amount of work. 

![image](https://github.com/ra3xdh/qucs_s/assets/4920080/5616a69f-a19e-4335-a9bf-286877b14db3)

**Comment by ra3xdh** [comment]
I have finished update of the toolbar icons. The result could be seen on the screenshot. I am planning to include updated icons in the next release. The following tasks are remaining:

* It's need to implement automatic generation of the component icons. This will allow to avoid redesign of more than 100 icons. 
* The diagram icons cannot be generated automatically. These 11 icons should be redrawn by hand.

**Comment by ra3xdh** [comment]
Here is the new toolbar look:
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/ac5c7780-2d35-45ed-a0a4-9c6ab165842b)

**Comment by ra3xdh** [comment]
See #323

**Comment by ra3xdh** [comment]
See #332 for diagram and paintings icons

**Comment by ra3xdh** [comment]
I have updated diagram icons. Here is the new application look. It is not possible to update remaining 250+ device icons manually. Automatic icons generator need to be implemented. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/158d3c2e-ec65-42d3-b48a-ebef407ab72b)

**Comment by ra3xdh** [comment]
See #334 for icons rendering. Here is the new application look.
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/2d658a18-45c1-4060-897b-28637a63bd04)

**Comment by ra3xdh** [comment]
New auto-generated icons after adjustment.
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/8e65e0ad-a1a9-4620-b7f4-4f9469807409)

**Comment by hugolundin** [comment]
Amazing work!

**Comment by ra3xdh** [comment]
Resolved with #332 and #334. New icons will be available since the next release. I have no possibility to check everything with 4k resolution hardware, but everything works fine using fullHD and scaling applied.

**Comment by hugolundin** [comment]
I can do a sanity check on my retina Mac later next week. But this seems fantastic, great job!

**Comment by hugolundin** [comment]
<img width="1552" alt="Screenshot 2023-10-23 at 23 03 43" src="https://github.com/ra3xdh/qucs_s/assets/9110669/b0a684a1-20d9-43b6-9354-a3fdf5e47f12">

The icons look great on my Macbook Air (with scaled resolution) now! Thank you!

**Comment by ra3xdh** [comment]
@hugolundin Thanks for testing on MacOS! I am planning to prepare the release packages by the end of this week.
