### ISSUE TITLE
Tracking qucs-s in the packaging ecosystem

### ISSUE THREAD

**Issue by luzpaz** [ra3xdh/qucs_s#306]
**Current snapshot of qucs-s in downstream package repos**:

<a href="https://repology.org/project/qucs-s/versions">
    <img src="https://repology.org/badge/vertical-allrepos/qucs-s.svg?columns=3" alt="Packaging status">
</a>

**Here are some attempts to update or implement qucs-s downstream**:

- [ ] Chocolatey (windows)
- [ ] Debian
- [ ] Gentoo (https://bugs.gentoo.org/891303)
- [X] nixpkgs https://github.com/NixOS/nixpkgs/issues/250576#event-10242240167
- [ ] OpenSUSE
- [ ] Raspbian
- [ ] Ubuntu
- [ ] winget (windows) https://github.com/microsoft/winget-pkgs/issues/118572
- [ ] wikipedia (create a page for qucs-s, any volunteers?)

**Comment by luzpaz** [comment]
Added link to previously opened Gentoo new package request: https://bugs.gentoo.org/891303

**Comment by ra3xdh** [comment]
> Added link to previously opened Gentoo new package request:

The Gentoo member has asked if the Qucs-S is ported to Qt6. Yes, the porting has been finished in 2.0.0. See #190. @luzpaz , please answer about this at the Gentoo forum.

**Comment by luzpaz** [comment]
bumped gentoo ticket again
