### ISSUE TITLE
touchstone file not working.

### ISSUE THREAD

**Issue by oe2lsp** [ra3xdh/qucs_s#392]
I either get an error massage or qucs-s terminates without any error message.

Qucs-s Version 2.1.0
Ngspice Version 41

two files attached:
[terminate.zip](https://github.com/ra3xdh/qucs_s/files/13546465/terminate.zip)
[error.zip](https://github.com/ra3xdh/qucs_s/files/13546491/error.zip)

Both touchstone files are working fine in qucs, the schematic files were created directly on qucs-s.
If there is any additional information needed, please let me know

**TODO**

- [x] Fix comments processing in touchstone files
- [x] Fix line continuation processing in touchstone files
- [x] Add support for MA format
- [x] Fix crash if tabs are used as delimiter #475 

_Originally posted by @oe2lsp in https://github.com/ra3xdh/qucs_s/issues/233#issuecomment-1838653385_

**Comment by oe2lsp** [comment]
thanks so far

**Comment by tomhajjar** [comment]
I found another issue. I edited the BFP780 s2p file to remove the comments but the test data is wrong. s11... s22 is always 0.5.

![2023-12-04_114258](https://github.com/ra3xdh/qucs_s/assets/102838604/bdfb4ba1-35a2-4882-8f2b-c4270a9f605e)

![2023-12-04_114032](https://github.com/ra3xdh/qucs_s/assets/102838604/9f002da1-f16d-4017-920a-a829b87b5e43)

[BFP780_test_prj.zip](https://github.com/ra3xdh/qucs_s/files/13549090/BFP780_test_prj.zip)

**Comment by tomhajjar** [comment]
The vast majority of manufacturer supplied S-parameter files use Mag/Angle. I would think s2spice support most formats.

**Comment by ra3xdh** [comment]
I will add the support for MA format in future versions. Please wait. I have updated TODO list.

**Comment by zergud** [comment]
please try current branch

**Comment by ra3xdh** [comment]
@zergud , Yes, now it is fixed.

**Comment by tomhajjar** [comment]
Can I get a Windows 64 version to continue testing? I have lot's of Qucs S-parameters test projects for comparison and s2spice.exe.

**Comment by ra3xdh** [comment]
The line continuation processing fixed by #522
