### ISSUE TITLE
Add GUI for Qucsconv

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#647]
The new version of Qucs-S will include QucsatorRF #370. The Qucsconv utility is a part of QucsatorRF. This tool operates only in CLI mode now. It would be good to add a simple GUI to Qucsconv in the *Tools* menu. 

**Update**

No new GUI for qucsconv is needed. It's need to improve the existing one. 

**TODO** list:

- [x] Move the *Import/Export data* dialog to *Tools* menu.
- [x] Allow to run it outside projects
- [x] Allow only valid in/out format pairs

**Comment by tomhajjar** [comment]
Sent email...

**Comment by tomhajjar** [comment]
The present user interface for Qucsconv is not well thought out. A new user wouldn't understand what file entries or drop down menu choices to make. At a minimum the file extensions should have been listed. Also what the drop down menu choices actually mean would help. I don't even know what some of them will do.

Will the new "Qucsconv-RF" still convert Spice files to Qucs schematics? Qucsconv only works for simple Spice files.

![2024-03-21_094430](https://github.com/ra3xdh/qucs_s/assets/102838604/b97b067e-125a-4d39-84e2-6b7f7ad1cfc2)

**Comment by ra3xdh** [comment]
> The present user interface for Qucsconv is not well thought out. 

I have never seen this dialog window in Qucs before. How to call it? 

> Will the new "Qucsconv-RF" still convert Spice files to Qucs schematics? 

Qucsconv from Qucsator-RF follows the state for Qucsator-0.0.20: https://github.com/qucs/qucsator I may consider adding some extensions in the future, but I cannot promise when exactly and what.

**Comment by tomhajjar** [comment]
Project->Import/Export Data. 

It needs a complete makeover to improve clarity and clear out the unneeded utility choices.

Qucs-0.0.20 has the s-parameter converter. It converts qucs.dat files from an s-parameter analysis to an *.s2p file, ?Not use how it handles more than 2 ports.

![2024-03-21_100646](https://github.com/ra3xdh/qucs_s/assets/102838604/aae2c540-08bc-47e9-b48c-c35efe4d6fba)

**Comment by ra3xdh** [comment]
> It needs a complete makeover to improve clarity and clear out the unneeded utility choices

Yes, the existing converter GUI needs improvement. It should be moved to *Tools* menu and allowed to be launched outside projects. Also it should allow only valid input/output pairs.

**Comment by tomhajjar** [comment]
The requirement for opening a Project first isn't too bad since it will save a lot of mouse clicks choosing the input file and indicate the directory where the output file is saved. The input file(s) will generally be in a Project file.

Unfortunately in Qucs when you click the "Browse" button it It points to the location where Qucs is installed instead of the chosen Project directory. Qucsconv should present the chosen Project directory first. 

![2024-03-21_103854](https://github.com/ra3xdh/qucs_s/assets/102838604/45171dbe-68d5-452c-911a-4f4c9f1fa3a2)

**Comment by tomhajjar** [comment]
I guess I have some documents referencing qucsconv to read...

![2024-03-21_114116](https://github.com/ra3xdh/qucs_s/assets/102838604/70b5cbb8-75ed-4b76-a61c-86aab65cfae3)

**Comment by tomhajjar** [comment]
The statements on this "Help" page seems wrong. Isn't "input" and "output" switched?
https://linux.die.net/man/1/qucsconv

"The software aims to support a variety of data formats and currently supports Qucs datasets, SPICE netlists, CITIfiles, Touchstone, ZVR, VCD and IC-CAP model files as **input** data format and CSV files, Qucs netlists, libraries and datasets as **output** data format."

**Comment by tomhajjar** [comment]
Using Qucsconv_rf:

Converting *.dat file to Touchstone S-parameter file is working

Converting SIMPLE 2SC3356.cir file to Qucs Library netlist is working AFAIK. What this file is useful for is unknown...

Converting SIMPLE 2SC3356.cir file to 2SC3356.sch is NOT working. This simple Spice file should easily convert into a sch file.

Attached is an old Qucs project. I created NE85633 HF Spice Model.sch using the qucsconv in QucsStudio.

NE85633=2SC3356

[2SC3356 Amplifiers_qucs_prj.zip](https://github.com/ra3xdh/qucs_s/files/14705703/2SC3356.Amplifiers_qucs_prj.zip)

**Comment by ra3xdh** [comment]
> Converting SIMPLE 2SC3356.cir file to 2SC3356.sch is NOT working

CIR to SCH conversion was never implemented in Qucsconv. SPICE netlist could be converted only Qucsator netlist, but not to XML schematic.

**Comment by ra3xdh** [comment]
The valid pairs for conversion are the following:
~~~
FORMAT: The input - output format pair should be one of the following:
  inputformat - outputformat
  spice       - qucs
  spice       - qucslib
  vcd         - qucsdata
  qucsdata    - csv
  qucsdata    - touchstone
  citi        - qucsdata
  touchstone  - qucsdata
  csv         - qucsdata
  zvr         - qucsdata
  mdl         - qucsdata
  qucsdata    - matlab
~~~

**Comment by ra3xdh** [comment]
> I created NE85633 HF Spice Model.sch using the qucsconv in QucsStudio.

I cannot backport features from QucsStudio to Qucs-S without permission of its developer. Even open parts of QucsStudio may be under copyright.

**Comment by ra3xdh** [comment]
> Converting SIMPLE 2SC3356.cir Spice file to Qucs Library netlist is working AFAIK. What this file is useful for is unknown...

This works only for files containing modelcards. The example of such file is here: https://ltwiki.org/index.php?title=Standard.bjt Running qucsconv on it will produce a valid library containing transistor models.

**Comment by tomhajjar** [comment]
I fully understand however I've converted multiple Spice files to *.sch using qucsconv in Qucs. The biggest problem has been missing sources so I end up using QucsStudio. I would have to dig through old projects. I saved multiple failed conversions.

These schematics are after I clean them up.

![2024-03-21_145849](https://github.com/ra3xdh/qucs_s/assets/102838604/709d82a4-4b37-43b3-b947-937c1806d5ec)
![2024-03-21_145828](https://github.com/ra3xdh/qucs_s/assets/102838604/b7262ef0-d720-4fb0-b646-5247d9512438)

**Comment by ra3xdh** [comment]
>  fully understand however I've converted multiple Spice files to *.sch using qucsconv in Qucs.

Am I understanding correct? Could you post CLI syntax to convert SPICE to SCH XML? Qucsconv from Qucs never supported this feature. There is no way to convert netlist to schematic. I suspect this may be either something undocumented or you can be using  Qucsconv from QucsStudio by mistake.

**Comment by ra3xdh** [comment]
I have inspected the sources, the qucsconv version from Qucs-0.0.20 release cannot produce SCH files, but the version from QucsStudio can.

**Comment by tomhajjar** [comment]
Using QucsStudio, this is the converted file for the IRFP250 MOSFET looks like after it has been partially cleaned up. 

![2024-03-21_155101](https://github.com/ra3xdh/qucs_s/assets/102838604/ba1e6219-faba-4354-8342-06ca09894269)

**Comment by ra3xdh** [comment]
As I wrote before, I cannot backport the features from open parts of QucsStudio without permission of its developer. I will try to contact Michael Margraf and ask about the license status of the open parts of QucsStudio.

**Comment by ra3xdh** [comment]
The import dialog redesign was made by #654. Here is the new dialog look:
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/9ac0b84c-9e6c-4aa6-ad6c-b51e0c42b20a)

**Comment by tomhajjar** [comment]
> As I wrote before, I cannot backport the features from open parts of QucsStudio without permission of its developer. I will try to contact Michael Margraf and ask about the license status of the open parts of QucsStudio.

There really isn't a need to convert Spice to Sch. QucsStudio can't convert the majority of Spice models successfully anyway. It was useful to use it for Qucs but not for Qucs-S.
