### ISSUE TITLE
Issues Editing Sub-circuit Symbols

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#750]
Still having issues editing and creating Sub-circuit Symbols. #739 didn't fix all the issues.

The small thin black "+" at 0,0 disappears during editing and gets replaced by a larger thick black "-". I then lose track of the "Centroid" for the symbol. I have to type Esc to get it to reappear but then I can't edit. It happens if you select any item(s) like a line and move it.

The Port labels ANODE/CATHODE are randomly disappearing, I can only get the the labels back if I go back to Schematic mode and then re-enter Symbol editing mode. Using "Undo" doesn't work. This happens in symbol editing mode if you select the entire diode symbol and then use "CTRL R".

In symbol editing mode if you select the entire diode symbol, move it and then use "CTRL R", the entire symbol disappears and "Undo" does nothing. I have to go back to Schematic mode and then re-enter Symbol editing mode. 

If I select an item and type "CTRL R" the item disappears. Doesn't matter if in schematic or symbol editing modes. "CTRL R" only works if I type it first and then select the item I want rotated. This is not the way it used to work.

If I type "CTRL R", Qucs-S is then "Stuck" in Rotate mode and I have to type "ESC". 

**TODO** list

- [x] fix coordinate center rendering in symbol mode #752 
- [x] fix undo operation in symbol editing mode #754 
- [x] disable rotate shortcut while moving graphics primitives in symbol editing mode 

![2024-06-11_144857](https://github.com/ra3xdh/qucs_s/assets/102838604/546669ca-b038-4508-822a-d9b6b98cc89a)

![2024-06-11_150241](https://github.com/ra3xdh/qucs_s/assets/102838604/838c0180-1263-49e2-8fdb-99ab43a3fa3d)

![2024-06-11_150907](https://github.com/ra3xdh/qucs_s/assets/102838604/9cd460e8-b2f9-4aea-9a84-82d1550f5519)

[SOD323_pkg.zip](https://github.com/user-attachments/files/15793656/SOD323_pkg.zip)

**Comment by wawuwo** [comment]
Hi! 

I've managed to reproduce two bugs and I'll try to provide fixes for them in the near future.

#### 1. A dash appears at 0,0 when anything on schematic is moved
  Steps to reproduce:
  1. Select any component from left panel and move cursor around schematic or using the mouse move any element already present on schematic

A small dash appears near the coordinates origin cross

#### 2. In symbol edit mode port labels disappear once you use the "Undo"
  Step to reproduce:
  1. Switch to symbol editing mode
  3. Ensure you have a port with label
  4. Do something (add a line for example)
  5. Hit Ctrl+Z
  
  Port labels disappear until switching to schematic mode and back to symbol mode.

<hr>

>if you select the entire diode symbol, move it and then use "CTRL R", the entire symbol disappears 


I couldn't reproduce this, sorry. Nothing disappears on my machine:

https://github.com/ra3xdh/qucs_s/assets/40355531/4392b12d-dd05-49a0-9fdc-5db111a874aa


>If I select an item and type "CTRL R" the item disappears. Doesn't matter if in schematic or symbol editing modes.

I cannot reproduce this one too. Both Mac and Linux machines don't have this problem:

https://github.com/ra3xdh/qucs_s/assets/40355531/516d2991-a692-42f4-a0b4-951abcf621e1


>If I type "CTRL R", Qucs-S is then "Stuck" in Rotate mode and I have to type "ESC".

I believe it has been always acting like this. I have the 24.1 version installed and hitting Ctrl+R in it "switches" you to "rotate mode", Ctrl+M to "mirror mode", etc.

**Comment by tomhajjar** [comment]
I have to wait for the next nightly...

**Comment by ra3xdh** [comment]
Fixed by #752 and #754.

**Comment by tomhajjar** [comment]
Downloaded the latest nightly. 

If I zoom in on a sub-circuit symbol, select a group of items, move them and rotate them using CNTRL-R they disappear for good. Undo does nothing...

![2024-06-13_133418](https://github.com/ra3xdh/qucs_s/assets/102838604/3cd278a2-d4de-4474-b04f-b02f32771e20)

**Comment by ra3xdh** [comment]
> If I zoom in on a sub-circuit symbol, select a group of items, move them and rotate them using CNTRL-R they disappear for good. Undo does nothing...

Sorry, I have checked both Linux and Windows versions and still cannot reproduce this. The rotation works as expected on my machine.

[Screencast_20240613_211848.webm](https://github.com/ra3xdh/qucs_s/assets/4920080/bc05ced4-b5f1-4f4f-ae0c-731cffa78837)

**Comment by tomhajjar** [comment]
I can reproduce the same issue in Qucs 0.0.19 and 0.0.20. Not sure what to make of it.

**Comment by wawuwo** [comment]
The only way to reproduce something similar I've found is to press Ctrl+R _while_ moving the elements.

The steps to reproduce are:
1. Select one or more elements on schematics or one or more paintings in symbol mode.
2. Begin moving them
3. Without releasing the left mouse button press Ctrl+R

The result:
1. "Rotation mode" turns on, cursor changes its appearance
1. Selected elements disappear completely and cannot be restored with the undo action

Is this the issue we're trying to find?

**Comment by tomhajjar** [comment]
That's the issue I have been seeing. It seems like it has existed for over decade in Qucs as well. Seems odd no one saw it before now.

**Comment by ra3xdh** [comment]
Yes, I understood how reproduce this now. All Qucs-S version are affected. The solution may be straightforward. It would be sufficient to disable rotate shortcut while moving symbol in symbol editing mode. I am reopening this.

**Comment by ra3xdh** [comment]
I have added TODO list for this.
