### ISSUE TITLE
Library extension

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#846]
I have recently discovered this website containing SPICE models for different devices: https://fotoelektronika.com/spice-models/ The most of these models could be converted to Qucs-S libraries. The models requires porting to Ngspice notation (replace `IF` by ternary operator etc.). 

The following models are especially interesting:

* Vacuum tube models
* PWM controller models

The presented PWM controller models (UC3844, TL494 etc.) don't contain LTspice digital gates extensions and should work with Ngspice after minor tweaks.  

**TODO** list from @ra3xdh:

- [x] Add Ge diodes library
- [x] Add Mixer ICs library (SA612 model)
- [x] Add PWM controller library (MC34063, UC384x, TL494) #855 
- [x] Update existing Tubes library
- [x] Add library with Neon bulb model 
- [x] Add MOC3052/MOC3063 models in Optocoupler.lib
- [x] Add ACPLK30T model #927

**Comment by ra3xdh** [comment]
I have tested the provided PWM controllers models, and it doesn't work with Ngspice. The Ngspice reads the model without error but then fails to converge or gives kilovolt outputs. Theses models requires significant effort to port them to Ngspice syntax.

**Comment by tomhajjar** [comment]
Can you post your project? The ngspice guys have made many changes to improve compatibility. They also have recommended changes to models.

**Comment by ra3xdh** [comment]
Here is the project. It is done using the latest snapshot build. The MC34063 device is taken from another place and works as expected. The both UC3483 and TL494 gives either zero or kilovolt output. I suppose the problem may come from the following line in the models:

~~~
.IC V(QINT,GND) 0
~~~ 

I have tried replacing this by setting IC on the capacitor connected to this node, but no result. I also see nested `IF` conditions in one source. I am not sure if NGspice supports this.

~~~
GQ  GND  QINT VALUE {IF(V(CLKI,GND)>{V(VCC,GND)/2},IF(V(D,GND)>{V(VCC,GND)/2},{V(VCC,GND)},-5),0)}
~~~

[PWM_controller_prj.zip](https://github.com/user-attachments/files/16285056/PWM_controller_prj.zip)

**Comment by ra3xdh** [comment]
I finally managed to get TL494 operational. The .IC directive required correction. Also setting `InitialDC=no` helps. The UC3843A model still be no result. 

![image](https://github.com/user-attachments/assets/ef86509b-0b0e-49da-b308-48ed163f3594)

[PWM_controller_prj.zip](https://github.com/user-attachments/files/16310953/PWM_controller_prj.zip)

**Comment by ra3xdh** [comment]
I have added MixerIC library containing SA612 model as part of #850. Everything works as expected with default Ngspice settings.

![image](https://github.com/user-attachments/assets/abb2b3e8-8bb1-426a-8cae-02f1a777c973)

**Comment by tomhajjar** [comment]
I will make a symbol for the Tl494.

I worked on the SA612 many years ago. Attached is my project. I made two different SA612 symbols but the colors and line widths don't conform to what we are using today.

![2024-07-19_074736](https://github.com/user-attachments/assets/5cf75172-745d-4566-9c1c-5f7c8eb8a0f9)
![2024-07-19_075244](https://github.com/user-attachments/assets/4c85b9c6-cd85-44b0-adbe-273b51b56d01)
![2024-07-19_075323](https://github.com/user-attachments/assets/1b8167ad-6960-4352-bbcd-ccfc807e9bb9)

[SA612_prj.zip](https://github.com/user-attachments/files/16311441/SA612_prj.zip)

**Comment by ra3xdh** [comment]
I have fixed the UC3843A model. There was a mistake in testbench schematic in PDF. The supply voltage should be in range from 9 to 15V. Also the DX diode model required a correction. The default BV value caused convergence error for Ngspice. The fixed model is attached. The other UC384x devices may be fixed in a similar way.

![image](https://github.com/user-attachments/assets/6624617d-4751-4b4d-9ea9-b647b1f5f21a)


[UC3843A.cir.txt](https://github.com/user-attachments/files/16313379/UC3843A.cir.txt)

**Comment by ra3xdh** [comment]
Summarizing all above, the PWM controller models could be assembled in a library. This library could be added in the upcoming release.

**Comment by ra3xdh** [comment]
I have added TODO list to this issue.

**Comment by tomhajjar** [comment]
First cut of the TL494 symbol. Since the device can be used to make multiple regulator topologies, no obvious way to make the symbol.

![2024-07-19_152511](https://github.com/user-attachments/assets/daeced0b-d6d2-416f-86dc-c21c02564fcd)

[TL494.zip](https://github.com/user-attachments/files/16316364/TL494.zip)

**Comment by ra3xdh** [comment]
PWM controller library implemented by #855.

**Comment by tomhajjar** [comment]
I made a small change to the TL494 symbol. PIN3, CMP->FBK

CMP was on an old schematic. FBK is on data sheet...

![2024-07-22_104941](https://github.com/user-attachments/assets/8c8c6890-c8e9-4737-90e5-1db2cda9257c)

[TL494.zip](https://github.com/user-attachments/files/16335744/TL494.zip)

**Comment by tomhajjar** [comment]
There is a Kicad example using the UC1825. I haven't tested it.

![2024-07-22_225943](https://github.com/user-attachments/assets/8929a502-2777-45c2-b57c-51ac7e390ac7)

[UC1825.zip](https://github.com/user-attachments/files/16343234/UC1825.zip)

**Comment by tomhajjar** [comment]
SG3525A is very similar and made by many companies. I'm looking into it.

**Comment by tomhajjar** [comment]
I have updated the Avago ACPLK30T Photo Voltaic Isolator. It would make a good addition to Optocoupler.lib

![2024-09-03_193951](https://github.com/user-attachments/assets/9c0ffe6f-9e32-401a-8f0c-5a2854c27841)
![2024-09-03_193936](https://github.com/user-attachments/assets/706a4319-dc73-496f-863b-73a820e07393)

[ACPLK30T_Photo_Voltaic_Isolator.zip](https://github.com/user-attachments/files/16858786/ACPLK30T_Photo_Voltaic_Isolator.zip)
